config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get "about" => "pages#about" #creates about_path

  get "anotherpage" => "pages#anotherpage"

  get "signup" => "pages#signup"

  get "login" => "pages#login"
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

	def about
	end

	def anotherpage
	end

	def signup
	end

	def login
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		This is where a colophon and a link might go.
		<%= link_to "Zombo.com", "http://zombo.com" %>
	</small>

</div>		

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
			<a class="navbar-brand" href="#">Branding!</a>
  </div>

	<div class="collapse navbar-collapse navbar-ex1-collapse">
		<ul class="nav navbar-nav navbar-right">
			<li>
				<%= link_to "Home", root_path %>
			</li>
			<li>
				<%= link_to "About the App", about_path %>
			</li>
			<li>
				<%= link_to "Another Page", anotherpage_path %>
			</li>	
			<li>
				<%= link_to 'Login', '#' %>
			</li>
		</ul>
	</div>
</nav>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Pinteresting</title>
<link href='http://fonts.googleapis.com/css?family=IM+Fell+DW+Pica' rel='stylesheet' type='text/css'>

		<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>

		<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	
	<body>
		<%= render 'layouts/header' %>
		
		<div class="container">
			<%= yield %>
		</div>
	
	</body>
</html>

app/views/pages/about.html.erb
<h1>About This App</h1>

<p>This website is a Ruby on Rails project </p>


<address>
<strong>Susan Skoog</strong><br>
Camelot Cohousing, Berlin, Massachusetts <br>
<abbr title="Email">e:</abbr> susan.skoog@gmail.com
</address>	<!--put an email icon here from font-awesome -->

app/views/pages/anotherpage.html.erb
<h1>Another Page</h1>

<p>
	Cras justo odio, dapibus ac facilisis in, egestas eget quam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam quis risus eget urna mollis ornare vel eu leo. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean lacinia bibendum nulla sed consectetur. </p>
	<p>

Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Sed posuere consectetur est at lobortis. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.
</p>	


<p>It's another .erb template for a html web page. erb is Embedded Ruby. So this is a meta-template.</p>

app/views/pages/home.html.erb
<div class="jumbotron">
		<h1>Heading Welcoming You Who Have Come To My Pinteresting Rails App.</h1>
		<p>Anything is possible at my rails app.</p>

		<p>Cliquez 
			<%= link_to "ici", "http://www.zombo.com", class: "btn btn-primary btn-lg" %> 
		</p>

		<p>
			<%= link_to "About this app", "about", class: "btn btn-primary btn-lg" %>
		</p>

		<p>
			<% link_to 'Another page!', "anotherpage", class: "btn btn-primary btn-lg" %>
		</p>

		<p>The only limit is yourself.</p>
</div>	